# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: myserverlesspj
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ethanp_serverless
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: myserverlesspj-bucket66
      localDir: UploadData

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET
          cors: false
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: /get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myserverlesspj-bucket66
