org: ethanp
app: myserverlesspj
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: myserverlesspj
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ethanp_serverless
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:*
          Resource: "*"

plugins:
  - serverless-s3-sync
  - serverless-webpack
  - serverless-add-api-key

package:
  individually: true

custom:
  tableName: player-points
  bucketName: myserverlesspj-bucket66
  webpackIncludeModules:
    forceExclude:
      - aws-sdk
  webpack:
    webpackConfig: ./webpack.config.js
    concurrency: ${opt:compile-concurrency, 6}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData
  apiKeys:
    - name: MyFirstApiKey

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET
          cors: false
  getPlayerScore:
    handler: handler.getPlayerScore
    events:
      - http:
          path: /get-player-score/{ID}
          method: GET
          cors: true
          private: true
  postPlayerScore:
    handler: handler.postPlayerScore
    events:
      - http:
          path: /post-player-score
          method: POST
          cors: false
  getFile:
    handler: handler.getFile
    events:
      - http:
          path: /get-file/{fileName}
          method: GET
          cors: false
  createFile:
    handler: handler.createFile
    events:
      - http:
          path: /post-file
          method: POST
          cors: false
  proxy:
    handler: handler.proxy
    events:
      - http:
          path: chuck-norris/{proxy+}
          method: ANY
          integration: http-proxy
          request:
            uri: https://api.chucknorris.io/{proxy}
            parameters:
              paths:
                proxy: true
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: /send-email
          method: POST
          cors: true
resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    MyAssumeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyAssumeRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
